# vim ft=yaml
# travis-ci.org definition for DataLad build
language: python

cache:
  - apt

matrix:
  include:
  - python: 2.7
  # no loop dev support on travis yet :-/ https://github.com/travis-ci/travis-ci/issues/2700
  #- python: 2.7
  #  env:
  #  - NOSE_WRAPPER="tools/eval_under_testloopfs"
  - python: 2.7
    # By default no logs will be output. This one is to test with log output at INFO level
    env:
    - DATALAD_LOGLEVEL=INFO
  - python: 2.7
    # By default no logs will be output. This one is to test with low level but dumped to /dev/null
    env:
    - DATALAD_LOGLEVEL=2
    - DATALAD_LOGTARGET=/dev/null
  - python: 2.7
    env:
    # to test operation under root since also would consider FS "crippled" due to
    # ability to rewrite R/O files
    - NOSE_WRAPPER="sudo -E"
    # no key authentication for root:
    - unset -v DATALAD_TESTS_SSH
  - python: 2.7
    env:
    - DATALAD_TESTS_NONETWORK=1
    # must operate nicely with those env variables set
    - http_proxy=
    - https_proxy=
  - python: 2.7
    env:
    - PYTHONPATH=$PWD/tools/testing/bad_internals/_scrapy/
  - python: 2.7
    # To make sure that operates correctly whenever dataset directories have symlinks
    # in their path.
    env:
    # Eventually we will get there, but atm causes a good number of failures
    # - TMPDIR="/tmp/sym ссылка"
    - TMPDIR="/tmp/sym link"
  - python: 2.7
    # To make sure that operates correctly whenever dataset directories have symlinks
    # in their path.
    env:
    # To make orthogonal test where it is not a symlink but a dir with spaces
    - TMPDIR="/tmp/d i r"
  - python: 3.3
  - python: 3.4
  # Those aren't yet ready since lxml I believe fails to install
  #- python: pypy
  #- python: pypy3
# not there -- don't try!
# - python: 3.5
# can't since coverage doesn't support it yet: https://bitbucket.org/ned/coveragepy/issues/391/getargspec-was-finally-removed-will-not-be
# - python: nightly

env:
  # to overcome problem with system-wide installed boto on travis
  # see https://github.com/travis-ci/travis-ci/issues/5246
  - BOTO_CONFIG=/tmp/nowhere
  - DATALAD_TESTS_SSH=1


script:
  - export | grep DATALAD
  - export
